[project]
name = "Dashify"
description = "A configurable terminal dashboard built with Textual."
version = "0.1.2"
authors = [
    {name = "Icecreambobcat",email = "icekingrex123@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14,<3.16"
keywords = ["dashboard", "terminal", "textual", "tui"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
]
dependencies = [
    "textual (>=7.5.0,<8.0.0)",
    "tomlkit (>=0.15.0,<0.16.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "psutil (>=7.2.2,<8.0.0)"
]

[project.urls]
Repository = "https://github.com/Icecreambobcat/dashify"
Issues = "https://github.com/Icecreambobcat/dashify/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pyinstaller (>=6.22.2,<7.0.0)",
    "pyright (>=1.1.411,<2.0.0)",
    "ruff (>=0.16.4,<0.17.0)"
]

[project.scripts]
dashify = "main:main"

[tool.poetry]
packages = [
    { include = "main.py", from = "src" },
    { include = "modules", from = "src" },
]
include = [
    { path = "defaults/dashify.toml", format = ["sdist", "wheel"] },
]

[tool.black]
target-version = ["py314"]
